version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cbl-workflow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17ad84fkq56u4"
s3_prefix = "cbl-workflow"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
